# Generated by Django 5.2.5 on 2025-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='middlename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
