# Generated by Django 5.2.5 on 2025-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0002_students_firstname_students_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='account_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='birthdate',
            field=models.DateField(default='2020-10-23'),
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=255, default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='lga',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='residential_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='residential_town',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='sort_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
