# Generated by Django 5.2.5 on 2025-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0003_students_account_name_students_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthdate',
            field=models.DateField(default='21-08-2025'),
        ),
    ]
