# Generated by Django 5.2.5 on 2025-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0004_alter_students_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='residential_address',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='residential_town',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='account_name',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='account_no',
            new_name='phoneno',
        ),
        migrations.RemoveField(
            model_name='students',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='students',
            name='country',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='students',
            name='sort_code',
        ),
        migrations.AddField(
            model_name='students',
            name='faculty',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='picture',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='programme',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
