# Generated by Django 5.2.5 on 2025-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0005_rename_residential_address_students_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=255, default=''),
        ),
    ]
