# Generated by Django 5.2.5 on 2025-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0006_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='session',
            field=models.TextField(default=''),
        ),
    ]
