# Generated by Django 5.2.5 on 2025-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0007_students_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthdate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
