# Generated by Django 5.2.5 on 2025-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0008_students_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiwesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.CharField(max_length=255)),
                ('startDate', models.CharField(max_length=255)),
                ('deadline', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
    ]
