# Generated by Django 4.2.4 on 2025-08-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0009_siwesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='siwesapp.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
