# Generated by Django 4.2.4 on 2025-08-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0010_siwesdetails_student_alter_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siwesdetails',
            name='deadline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='endDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='faculty',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='session',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='startDate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
