# Generated by Django 4.2.4 on 2025-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0011_alter_siwesdetails_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siwesdetails',
            name='student',
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='matricno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
