# Generated by Django 4.2.4 on 2025-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0012_remove_siwesdetails_student_siwesdetails_matricno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
