# Generated by Django 4.2.4 on 2025-08-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0013_locationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetails',
            name='location_id',
            field=models.IntegerField(default=0),
        ),
    ]
