# Generated by Django 4.2.4 on 2025-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0014_locationdetails_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='payment_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
