# Generated by Django 4.2.4 on 2025-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0015_siwesdetails_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siwesdetails',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='students',
            name='payment_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
