# Generated by Django 4.2.4 on 2025-08-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0016_remove_siwesdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siwesdetails',
            name='deadline',
            field=models.DateField(default='2025-08-28'),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='endDate',
            field=models.DateField(default='2025-08-28'),
        ),
        migrations.AlterField(
            model_name='siwesdetails',
            name='startDate',
            field=models.DateField(default='2025-08-28'),
        ),
    ]
