# Generated by Django 4.2.4 on 2025-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0018_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='siwes_address',
            field=models.TextField(default=''),
        ),
    ]
