# Generated by Django 4.2.4 on 2025-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0019_paymentdetails_location_paymentdetails_siwes_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='reference_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
