# Generated by Django 4.2.4 on 2025-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0020_alter_paymentdetails_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='amount2',
            field=models.FloatField(default=0),
        ),
    ]
