# Generated by Django 4.2.4 on 2025-08-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0021_paymentdetails_amount2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
    ]
