# Generated by Django 4.2.4 on 2025-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0022_remove_paymentdetails_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='siwes_address',
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='siwes_address',
            field=models.TextField(default=''),
        ),
    ]
