# Generated by Django 4.2.4 on 2025-08-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0023_remove_paymentdetails_siwes_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
