# Generated by Django 4.2.4 on 2025-08-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0024_students_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='title',
        ),
    ]
