# Generated by Django 4.2.4 on 2025-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0025_remove_students_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
