# Generated by Django 4.2.4 on 2025-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0026_students_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='location_id',
            field=models.IntegerField(default=0),
        ),
    ]
