# Generated by Django 4.2.4 on 2025-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0027_siwesdetails_amount_siwesdetails_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=255)),
                ('facultyCode', models.CharField(max_length=255)),
            ],
        ),
    ]
