# Generated by Django 4.2.4 on 2025-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0028_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=255)),
                ('departmentCode', models.CharField(max_length=255)),
                ('facultyCode', models.CharField(max_length=255)),
            ],
        ),
    ]
