# Generated by Django 4.2.4 on 2025-09-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0029_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='middlename',
        ),
    ]
