# Generated by Django 4.2.4 on 2025-09-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0030_remove_students_middlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='othernames',
        ),
    ]
