# Generated by Django 4.2.4 on 2025-09-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0031_rename_lastname_students_othernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='firstname',
            new_name='surname',
        ),
    ]
