# Generated by Django 4.2.4 on 2025-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0033_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
