# Generated by Django 4.2.4 on 2025-09-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0034_alter_students_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='firstname',
            new_name='othernames',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='lastname',
            new_name='surname',
        ),
    ]
