# Generated by Django 4.2.4 on 2025-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0035_rename_firstname_paymentdetails_othernames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthdate',
            field=models.DateField(default='2000-12-02'),
        ),
    ]
