# Generated by Django 4.2.4 on 2025-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0036_alter_students_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthdate',
            field=models.TextField(default=''),
        ),
    ]
