# Generated by Django 4.2.4 on 2025-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0037_alter_students_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='state_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='town',
            field=models.CharField(default='', max_length=255),
        ),
    ]
