# Generated by Django 4.2.4 on 2025-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0038_students_city_students_state_address_students_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='city',
        ),
        migrations.RemoveField(
            model_name='students',
            name='state_address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='street',
        ),
        migrations.RemoveField(
            model_name='students',
            name='town',
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='state_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='town',
            field=models.CharField(default='', max_length=255),
        ),
    ]
