# Generated by Django 4.2.4 on 2025-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0039_remove_students_city_remove_students_state_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='phoneno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
