# Generated by Django 4.2.4 on 2025-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0040_paymentdetails_email_paymentdetails_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatricNo', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('OtherNames', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Faculty', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Discipline', models.CharField(max_length=255)),
                ('Programme', models.CharField(max_length=255)),
                ('Level', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('PictureLink', models.TextField()),
            ],
        ),
    ]
