# Generated by Django 4.2.4 on 2025-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0041_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='MatricNo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
