# Generated by Django 4.2.7 on 2025-12-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0042_alter_studentdetails_matricno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='level',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='phoneno',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='students',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='students',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='picture',
        ),
    ]
