# Generated by Django 4.2.7 on 2025-12-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0043_rename_level_students_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='level',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='phone',
            field=models.TextField(default=''),
        ),
    ]
