# Generated by Django 4.2.7 on 2025-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0044_siwesdetails_email_siwesdetails_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='accountname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='accountno',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='bankname',
            field=models.TextField(default=''),
        ),
    ]
