# Generated by Django 4.2.7 on 2025-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0045_siwesdetails_accountname_siwesdetails_accountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='bankcode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='sortcode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='whatsapp_phone',
            field=models.TextField(default=''),
        ),
    ]
