# Generated by Django 4.2.7 on 2025-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0046_siwesdetails_bankcode_siwesdetails_sortcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='othernames',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='surname',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='fullname',
            field=models.TextField(default=''),
        ),
    ]
