# Generated by Django 4.2.7 on 2025-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0047_remove_paymentdetails_othernames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
