# Generated by Django 4.2.7 on 2025-12-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0048_paymentdetails_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
