# Generated by Django 4.2.7 on 2026-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0051_students3_delete_students2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('othernames', models.CharField(default='', max_length=255)),
                ('matricno', models.CharField(max_length=255)),
                ('programme', models.TextField(default='')),
                ('faculty', models.TextField(default='')),
                ('department', models.TextField(default='')),
                ('gender', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('lga', models.CharField(default='', max_length=255)),
                ('session', models.TextField(default='')),
                ('password', models.CharField(default='password', max_length=255)),
                ('payment_status', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Students3',
        ),
    ]
