# Generated by Django 4.2.7 on 2026-01-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siwesapp', '0055_students7_delete_students6'),
    ]

    operations = [
        migrations.AddField(
            model_name='siwesdetails',
            name='othernames',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siwesdetails',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
